### ISSUE TITLE
Smart Doors appears broken in V10

### ISSUE THREAD

**Issue by minakitty** [manuelVo/foundryvtt-smart-doors#28]
Like it says on the tin. With Smart Doors active, players and GM had no door icon to click on to open, but with it disabled, doors are appearing like they would in an unmodded system. Don't have a lot to go off of to suggest why, especially with all the other module issues we've had today.

Foundry V10 Build 284
Pathfinder 1 0.82.1
Smart Doors 1.3.3

**Comment by Rubengam3r** [comment]
I can duplicate the issue as well. With Smart Doors active the icons for the doors are gone.
Foundry V10 Build 284
Smart Doors 1.3.3
DnD5e 2.0.2

**Comment by oestred** [comment]
confirmed same issue, following

**Comment by CasualTerror** [comment]
Can confirm

**Comment by FluffyRopeBunny** [comment]
hope we get word on rather an update would be coming soon

**Comment by manuelVo** [comment]
I'm sorry, but it's hard to say. Currently, porting Drag Ruler has higher priority (as it's a lot more popular) and unfortunately that's been a bunch of work so far (though it's drawing to a close). Once Drag Ruler is ported Smart Doors will be the next module in the priority order. Giving a date at this point is impossibly tough, since I haven't looked at Smart Doors yet and don't know how much work porting that module will be.

**Comment by manuelVo** [comment]
Smart Doors is now available for Foundry v10.
